apiVersion: v1
kind: Namespace
metadata:
  name: mynamespace2
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
  namespace: mynamespace2
spec:
  hard:
    requests.cpu: "2"
    requests.memory: "2Gi"
    limits.cpu: "4"
    limits.memory: "4Gi"
