apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dummy-app.fullname" . }}
  labels:
    app: {{ include "dummy-app.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "dummy-app.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "dummy-app.name" . }}
    spec:
      containers:
        - name: stress
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - -cpus
            - "{{ .Values.stress.cpus }}"
            - -mem-total
            - "{{ .Values.stress.memTotal }}"
            - -mem-swap
            - "{{ .Values.stress.memSwap }}"
            - -timeout
            - "{{ .Values.stress.timeout }}"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}

        - name: cadvisor
          image: "{{ .Values.monitor.repository }}:{{ .Values.monitor.tag }}"
          imagePullPolicy: {{ .Values.monitor.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
