{{- if .Values.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "dummy-app.fullname" . }}
  labels:
    app: {{ include "dummy-app.name" . }}
spec:
  to:
    kind: Service
    name: {{ include "dummy-app.fullname" . }}
  port:
    targetPort: http
  tls:
    termination: edge
  {{- if .Values.route.host }}
  host: {{ .Values.route.host }}
  {{- end }}
{{- end }}