replicaCount: 1

image:
  repository: vish/stress
  tag: latest
  pullPolicy: IfNotPresent

monitor:
  repository: gcr.io/cadvisor/cadvisor
  tag: latest
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "256Mi"

stress:
  cpus: "1"
  memTotal: "50Mi"
  memSwap: "0"
  timeout: "0"

service:
  type: ClusterIP
  port: 8080
